---

- hosts: all
  roles:
    - asa_password_reset
  vars_prompt:
    - name:   "asa_fqdn"
      prompt: "What's the FQDN or IP address of the ASA firewall?"
      private: false
    - name:   "login_username"
      prompt: "What's your SSH username?"
      private: false
    - name:   "login_password"
      prompt: "What's your SSH password?"
    - name:   "enable_password"
      prompt: "What's your enable password?"
  vars:
    ansible_user:          "{{ login_username }}"
    ansible_ssh_pass:      "{{ login_password }}"
    ansible_become_pass:   "{{ enable_password }}"
    ansible_host:          "{{ asa_fqdn }}"
    ansible_become:        yes
    ansible_become_method: enable
    ansible_network_os:    asa
  vars_files:
    - /extra-vars.yml

